services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    env_file:
      - .env
    #   REDIS_PASSWORD: $REDIS_PASSWORD
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASS
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    build: .
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - .env
    environment:
      DATABASE_URL: $DATABASE_URL
      REDIS_URL: $REDIS_URL
      RABBITMQ_URL: $RABBITMQ_URL
      SECRET_KEY: $SECRET_KEY
    ports:
      - "8000:8000"
    restart: on-failure

volumes:
  db_data:
